name: Release KDG Browser

on:
  push:
    tags:
      - 'v*' # Триггер при создании тега, начинающегося с "v" (например, v3.2.0)
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Требуемая версия Node
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build:win

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist-package/KDG Browser Setup *.exe
            dist-package/latest.yml
          tag_name: ${{ github.ref_name }}
          name: KDG Browser ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
